# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            ModbusScope - GraphViewer
baseurl:          /
imageurl:					public/images

paginate:         5
